version: 2
jobs:
  build:
    working_directory: ~/DevOps/estimeo-highlights-sample/
	docker:
		- image: circleci/node:4.8.2
	steps:
		- checkout
		- run: echo "hello world"
		- run: sudo npm install -g npm@latest
		- run: npm install
		- run: npm run build
		- run: npm run test